# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockle < Formula
  desc "Simple security auditing, helping build the Best Docker Images"
  homepage "https://github.com/goodwithtech/dockle"
  version "0.3.9"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/goodwithtech/dockle/releases/download/v0.3.9/dockle_0.3.9_macOS-64bit.tar.gz"
    sha256 "f4403b1359c7792224f60678883fcc83934cf38d7a4d51aa0cc61dcce134f513"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/goodwithtech/dockle/releases/download/v0.3.9/dockle_0.3.9_Linux-64bit.tar.gz"
    sha256 "7581e7f338b86674289d818dbfe1ab76831b774fa6160f98d22eb0ac13aca672"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/goodwithtech/dockle/releases/download/v0.3.9/dockle_0.3.9_Linux-ARM64.tar.gz"
    sha256 "58468d3ff61c2f2cfee0ba272e386aa6191129b97ded1b07053057ad67b02de0"
  end

  def install
    bin.install "dockle"
  end

  test do
    system "#{bin}/program --version"
  end
end
