# This file was generated by GoReleaser. DO NOT EDIT.
class Dockle < Formula
  desc "Simple security auditing, helping build the Best Docker Images"
  homepage "https://github.com/goodwithtech/dockle"
  version "0.3.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/goodwithtech/dockle/releases/download/v0.3.1/dockle_0.3.1_macOS-64bit.tar.gz"
    sha256 "f31c2d2181292a750897e7473965a612932910870f11771df714f32c3246e527"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/goodwithtech/dockle/releases/download/v0.3.1/dockle_0.3.1_Linux-64bit.tar.gz"
      sha256 "4598749372d51707f34ba42295cfa58a4f7fc1686451a5153fd15be521a15120"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goodwithtech/dockle/releases/download/v0.3.1/dockle_0.3.1_Linux-ARM64.tar.gz"
        sha256 "de8a9e1d22f9bde9a6567bd3d6c0aade73c2bdaa59295a9f294af9febc01b736"
      else
      end
    end
  end

  def install
    bin.install "dockle"
  end

  test do
    system "#{bin}/program --version"
  end
end
