# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockle < Formula
  desc "Simple security auditing, helping build the Best Docker Images"
  homepage "https://github.com/goodwithtech/dockle"
  version "0.3.15"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goodwithtech/dockle/releases/download/v0.3.15/dockle_0.3.15_macOS-64bit.tar.gz"
      sha256 "ba3b25cf2af2f1570bfc1a315006706005d0ff19a50abcecec9f392cc6c086e4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/goodwithtech/dockle/releases/download/v0.3.15/dockle_0.3.15_macOS-ARM64.tar.gz"
      sha256 "ab39e7350c1de247089c78f98b541ef4e3facc74d44111553e8fcadf931fb0c7"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goodwithtech/dockle/releases/download/v0.3.15/dockle_0.3.15_Linux-64bit.tar.gz"
      sha256 "ff5f630dd37aa4518d0f9aef42d61f4bf415932730d86f96c74ae9a32c551aee"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goodwithtech/dockle/releases/download/v0.3.15/dockle_0.3.15_Linux-ARM64.tar.gz"
      sha256 "02c361bbed297b19fc4d9c64811dcf31368715b874e30d2be2fdae004c50196c"
    end
  end

  def install
    bin.install "dockle"
  end

  test do
    system "#{bin}/program --version"
  end
end
