# This file was generated by GoReleaser. DO NOT EDIT.
class Dockertags < Formula
  desc "docker container tag viewer"
  homepage "https://github.com/goodwithtech/dockertags"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/goodwithtech/dockertags/releases/download/v0.1.0/dockertags_0.1.0_macOS-64bit.tar.gz"
    sha256 "a0528198d61fa5fc733239b090d5294107c47a495ca80de5f18da96e9657685b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/goodwithtech/dockertags/releases/download/v0.1.0/dockertags_0.1.0_Linux-64bit.tar.gz"
      sha256 "c3ed8ca2c8c7e61a1de9804531a6767f32ebf0ad409931d4ff969e6d0c1e9840"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goodwithtech/dockertags/releases/download/v0.1.0/dockertags_0.1.0_Linux-ARM64.tar.gz"
        sha256 "a4d5ef6de4d13909065c129748eb04cb3066bcbbc235ca477865c72c0256050f"
      else
      end
    end
  end

  def install
    bin.install "dockertags"
  end

  test do
    system "#{bin}/program --version"
  end
end
