# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockertags < Formula
  desc "a CLI tool for fetching container image tags."
  homepage "https://github.com/goodwithtech/dockertags"
  version "0.1.6"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/goodwithtech/dockertags/releases/download/v0.1.6/dockertags_0.1.6_macOS-64bit.tar.gz"
    sha256 "74cb8bdc60ab202344f5e446f4d2547f8716bc8473968741f6fe3da33840fad8"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/goodwithtech/dockertags/releases/download/v0.1.6/dockertags_0.1.6_Linux-64bit.tar.gz"
    sha256 "c6a80e71dd7cbd250da2d19f88e1d20d199abd034e4a453cd12a3d6007cd9938"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/goodwithtech/dockertags/releases/download/v0.1.6/dockertags_0.1.6_Linux-ARM64.tar.gz"
    sha256 "967ceaf4ea08cda136acfa39ee7ba67e4e99b5a29dea749edc6c1682e97e7a14"
  end

  def install
    bin.install "dockertags"
  end

  test do
    system "#{bin}/program --version"
  end
end
