# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlboiler < Formula
  desc "Generate a Go ORM tailored to your database schema."
  homepage "https://github.com/volatiletech/sqlboiler"
  version "4.4.5"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/goodwithtech/sqlboiler/releases/download/v4.4.5/sqlboiler_4.4.5_macOS-64bit.tar.gz"
    sha256 "5a0e3bfc65dfcda39ef4e974303acb66a9d4874437bea0334521e22fe713599a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/goodwithtech/sqlboiler/releases/download/v4.4.5/sqlboiler_4.4.5_macOS-ARM64.tar.gz"
    sha256 "381816837c081be6492a133927dc283b2358a7cdfe2480b159cc34bdc090e0a6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/goodwithtech/sqlboiler/releases/download/v4.4.5/sqlboiler_4.4.5_Linux-64bit.tar.gz"
    sha256 "56c4e47d4cbe3d5b141f48119a2afcece73f424050541c351bacb90a4fdaf027"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/goodwithtech/sqlboiler/releases/download/v4.4.5/sqlboiler_4.4.5_Linux-ARM64.tar.gz"
    sha256 "5496b84b6d8dd4ac15d1bb2fd93f630bc3f240c5e5814284acc4301843c1ac8f"
  end

  def install
    bin.install "sqlboiler"
  end

  test do
    system "#{bin}/program --version"
  end
end
